sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: ecsam/octomap_point_cloud_transformed
    #    point_cloud_topic: d435i/depth/point_cloud
    max_range: 2.0
    point_subsample: 1
    padding_offset: 0.04
    padding_scale: 1.0
    max_update_rate: 6.0
    filtered_cloud_topic: ecsam/octomap_point_cloud/octomap_filtered
